### PR TITLE
Remove output of the outlook lookup

### LINKED ISSUE #25: Remove message that Outlook process was not found
On Windows I get this:

````
julia> using ExcelReaders
INFO: Precompiling module ExcelReaders...
INFO: Installing xlrd via the Conda package...
Get-Process : Cannot find a process with the name "Outlook". Verify the process name and call the cmdlet again.
At line:1 char:1
+ Get-Process Outlook
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Outlook:String) [Get-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.GetProcessCommand

Fetching package metadata: ....
````

This is on a system with no Outlook installed. The line that starts with ``get-process`` is red, indicating an error. Would be nice if that red output could somehow be suppressed. Not urgent, though, this is more aesthetic.

### PR DESCRIPTION
**Pull request by Luthaf**
Fix #25

### CODE REVIEW

**Comment by Luthaf** [comment]
This does not works (cf the appveyor output), and I do not have a windows machine to test. Some help would be appreciated!

File: src/Conda.jl [hunk 1]
```diff
@@ -104,7 +104,7 @@ end
 "Install miniconda if it hasn't been installed yet; _install_conda(true) installs Conda even if it has already been installed."
 function _install_conda(force=false)
     @windows_only begin
-          if try success(`powershell "Get-Process Outlook"`); catch; false; end
+          if try success(`powershell "Get-Process Outlook"` |> DevNull); catch; false; end
```
Comment (stevengj) [inline src/Conda.jl]: I think you need
```jl
success(pipeline(`powershell "Get-Process Outlook"`, stdout=DevNull, stderr=DevNull))
```
?

**Comment by Luthaf** [comment]
That seems to work, thanks!
